CREATE SEQUENCE CUSTOMER_ID_SEQ
  START 1
  INCREMENT BY 1;
CREATE TABLE CUSTOMER (
  ID         BIGINT PRIMARY KEY NOT NULL,
  FIRST_NAME VARCHAR(20)        NOT NULL,
  LAST_NAME  VARCHAR(25)        NOT NULL
);

CREATE SEQUENCE NOTE_ID_SEQ
  START 1
  INCREMENT BY 1;
CREATE TABLE NOTE (
  ID           BIGINT PRIMARY KEY                   NOT NULL,
  TITLE        VARCHAR(100)                         NOT NULL,
  PRIVATE_NOTE VARCHAR(255)                         NOT NULL,
  ARRANGEMENTS TEXT                                 NOT NULL,
  CREATED_DATE TIMESTAMP                            NOT NULL,
  CUSTOMER_ID  BIGINT REFERENCES CUSTOMER (ID)      NOT NULL
);